services:
  - docker

before_install:
  - docker build -t katedou/frontend -f ./exercise/frontend/Dockerfile.dev ./exercise/frontend/

script:
  - cd ./exercise/frontend
  - docker run -e CI=true katedou/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-710128592938"
  bucket_path: "docker-frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY